# Generated by Django 4.2.4 on 2023-09-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_anime_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='completo',
            field=models.BooleanField(default=False),
        ),
    ]
